#!/bin/bash
# libevent 
# Author: lufei
# Date: 2019年 08月 08日 星期四 15:27:22 CST
# 
# run check point with  runfunc or run_key_func
source common.sh
source test.sh

tmpdir=$TMPDIR/src

createfile()
{
cat > $tmpdir/hello.cpp << EOF
#include <stdio.h>
#include <iostream>
#include <event.h>

using namespace std;

// 定时器事件回调函数
void OnTime(int sock, short event, void *arg)
{
    cout << "Hello, world." << endl;

    struct timeval tv;
    tv.tv_sec = 1;
    tv.tv_usec = 0;
    // 重新添加定时事件（定时事件触发后默认自动删除）
    event_add((struct event*)arg, &tv);
}

int main()
{
    // 初始化
    event_init();

    struct event evTimer;
    // 设置定时事件
    evtimer_set(&evTimer, OnTime, &evTimer);

    struct timeval tv;
    tv.tv_sec = 1;
    tv.tv_usec = 0;
    // 添加定时事件
    event_add(&evTimer, &tv);

    // 事件循环
    event_dispatch();

    return 0;
}
EOF

}
clean()
{
rm -rf $tmpdir
}


run_key_func mkdir -p $tmpdir
run_key_func cd $tmpdir
run_key_func createfile

runfunc c++ hello.cpp -o hellocpp -levent
runfunc ./hellocpp

runfunc clean
