#!/bin/bash
# mpich 
# Author: lufei
# Date: 2019年 09月 23日 星期一 10:25:34 CST
# 
# Attention: run check point with  runfunc or run_key_func
# 
# Description:
# 

source common.sh
source test.sh


tst_dir=$TMPDIR/src

genfile(){



mkdir -p $tst_dir || return 2
cat > $tst_dir/hello.c << EOF
# include <stdio.h>
int main(void){
printf("Hello,world.\n");
return 0;
}
EOF

}

testfunc1(){
cd $tst_dir
gcc hello.c -o hello || return 1
/usr/lib64/mpich/bin/mpiexec -n 4 ./hello
}
main()
{

run_key_func chk_rpm_exists mpich-3.0
run_key_func genfile
run_key_func testfunc1
}


main
