#!/bin/bash
# openmpi 
# Author: lufei
# Date: 2019年 08月 12日 星期一 13:23:14 CST
# 
# run check point with  runfunc or run_key_func
source common.sh
source test.sh

tmpdir=$TMPDIR/src


createfile()
{
cat > $tmpdir/hello_mpi.c << EOF
#include <mpi.h>
#include <stdio.h>

int main(int argc, char** argv) {
    MPI_Init(NULL, NULL);

    int world_size;
    MPI_Comm_size(MPI_COMM_WORLD, &world_size);

    int world_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

    char processor_name[MPI_MAX_PROCESSOR_NAME];
    int name_len;
    MPI_Get_processor_name(processor_name, &name_len);

    printf("Hello world from processor %s, rank %d out of %d processors\n",
           processor_name, world_rank, world_size);

    MPI_Finalize();
}
EOF
}

clean()
{
rm -rf $tmpdir
}

run_key_func mkdir -p $tmpdir
run_key_func cd $tmpdir
run_key_func createfile
runfunc /usr/lib64/openmpi/bin/mpicc hello_mpi.c -o hello_mpi
runfunc /usr/lib64/openmpi/bin/mpirun --allow-run-as-root -np 4 hello_mpi

runfunc clean
